version: '2'
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/app
    command: gradle linuxTest 
    volumes_from:
     - caches

  caches:
    image: centos:7
    volumes:
      - ~/.gradle:/home/gradle/.gradle:rw
      - ~/.konan:/root/.konan:rw

